# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  linting:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/clagraff/raven
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u gopkg.in/alecthomas/gometalinter.v2
      - run: gometalinter.v2 --install
      - run: gometalinter.v2 --enable-all --disable gochecknoglobals --disable gocyclo --exclude=".*_test.go" ./...

  tests:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/clagraff/raven
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v --coverprofile cover.out ./...

  build:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/clagraff/raven
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u github.com/mitchellh/gox
      - run: gox --output="artifacts/{{.Dir}}_{{.OS}}_{{.Arch}}"


  publish:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/clagraff/raven
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run: go get -v -t -d ./...
      - run: go get github.com/tcnksm/ghr
      - run:
          name: "Publish"
          command: |
            VERSION=$(go run main.go version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - linting
      - tests
      - build:
          requires:
            - linting
            - tests
      - publish:
          requires:
            - build
